### PR TITLE
Brush up to storage.k8s.io/v1 API (K8S >= 1.19)

### PR DESCRIPTION
**Pull request by zer0def**
[Due to the `storage.k8s.io/v1beta1` API no longer being served by K8S 1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22), it requires a bit of an update to function with `storage.k8s.io/v1`. However, CSIDriver in that API has only been added to K8S 1.19, raising the minimum supported version.

### CODE REVIEW

**Comment by snickell** [comment]
@zer0def thanks for updating this! I've merged your changes into my local branch, and am testing with both minikube and gke. I'll report on findings, hopefully that will make it easier for @wunderio to merge.

**Comment by zer0def** [comment]
Hey @snickell, how did your tests go? Generally tested it against upstream K8S, but not sure whether this breaks on peculiar distros, like GKE.

**Comment by Jancis** [comment]
Thank You for creating this. Since configurations might break pre-1.19 clusters, may I suggest moving old yamls to some subfolder (i.e. `deploy/kubernetes/1.13`) and putting patched versions in another (i.e. `deploy/kubernetes/1.19`)?

**Comment by zer0def** [comment]
Updated per request.

**Comment by Jancis** [comment]
Was finally able to test this on 1.22. There was just one single thing that i'd change, having controller replicas back to 1. I'll change that in a separate commit as I found out installation instructions are also a bit screwed up too (I have not used `deploy/kubernetes` resources since initial commit because they were transformed into our [helm chart](https://github.com/wunderio/charts/tree/master/csi-rclone)). 

Thank You for contribution!

**Pull request merged**
